# DENIZENS are helpful, interactive Citizens!  Denizens run off of mini scripts with steps and events.
# They can be used in hundreds of different ways, from tutorials, to questing, to administrating and more!
# 
# Timeline: Beta 1 -- All functionality used in this example file.
#           Beta 2 -- Complete functionality of additional behaviors/requirements/triggers listed.
#           1.0 -- Bug fixes from Beta.
#           1.5 -- In-game Script editor.
# 
# 
# Default Denizen options let you tweak the specifics of your Denizens.

debug_mode: true
interact_delay_in_ticks: 10
npc_chat_range_in_blocks: 10
player_to_npc_chat_range_in_blocks: 2
player_to_npc_shout_range_in_blocks: 15
engage_timeout_in_seconds: 15
player_chat_to_npc: You say to <NPC>, <TEXT>
player_chat_to_npc_bystander: <PLAYER> says to <NPC>, <TEXT>
npc_chat_to_player: <NPC> says to you, <TEXT>
npc_chat_to_player_bystander: <NPC> says to <PLAYER>, <TEXT>
npc_whisper_to_player: <NPC> whispers to you, <TEXT>
npc_whisper_to_player_bystander: <NPC> whispers something to <PLAYER>.
npc_shout_to_player: <NPC> shouts at you, <TEXT>
npc_shout_to_player_bystander: <NPC> shouts at <PLAYER>, <TEXT>
chat_color: white
whisper_color: gray
shout_color: red
narrate_color: green
announce_color: yellow


Denizens:
  Jakob:
    Interact Scripts:
    - 0 Jacob the Fisherman
    - 10 Jakob's Perdicment, Part 1
    - 20 Jakob's Perdicment, Part 2
    - 30 Jakob's Perdicment, Part 5
    Activity Scripts:
    - 0 At home
    - 10 Sleeping
    - 20 Trying to fish
    - 30 Frantic
    - 30 Congratulate
    - 30 A big thanks
    Important Locations:
      "Home":
        Type: Cuboid
        Cuboid:
      "Fishing Hole":
        Type: Cuboid
        Cuboid:
      "Sleeping":
        Type: Location
        Location: 
    
    
    
    
    
    
    
    