# Whether debug information about Denizen should appear in the
# server console
Debug:
  Show: true
  ex command help: true
  Console width: 60

Scripts:
  World:
    Events:
      On player chats:
        # Whether to use the dangerous 'async' chat event (not recommended!)
        Use asynchronous event: false
      On time changes:
        Frequency of check: 250t
  Queue speed: 0.5s
  Scripts location:
    Use default script folder: true
    Alternative folder path: 'plugins/Denizen'
  Load scripts in subfolders: true

# The default options for new Denizen NPCs

# Whether to spawn NPCs with given traits, and what settings to have by default
Traits:
  Health:
    Enabled: false
    Respawn:
      Enabled: true
      Delay: 10s
    Animated death:
      Enabled: false

# Whether triggers are on by default, and their individual settings
Triggers:
  Chat:
    Enabled: true
    Use asynchronous event: false
    Cooldown: 2s
    Range: 3
    Overhearing range: 4
    Prerequisites:
      Must be looking in direction of NPC: true
      Must be able to see NPC: true
    Formats:
      Player to NPC: "You -> <npc.name.nickname>: <text>"
      Player to NPC overheard: "<player.name> -> <npc.name.nickname>: <text>"
    Appears globally:
      If triggers missing: true
      If triggers failed: false
      If NPC uninteractable: true
  Click:
    Enabled: true
    Cooldown: 2s
    Allows left click: false
  Damage:
    Enabled: false
    Cooldown: 0.5s
  Proximity:
    Enabled: false
    Cooldown: 1s
    Range: 10

Commands:
  Engage:
    # the default timeout for engage, if not specifically set otherwise
    Timeout: 150s
  while:
    # how many times the WHILE command can loop before it gives up
    # Set to 0 for infinite
    max-loops: 10000

# The version of this configuration file, used to check if your
# configuration file is outdated or too new
Config:
  Version: 6
