# The default number of ticks between commands in interact scripts
# Recommended values are between 5 and 15
Interact Delay in Ticks: 7

# The number of seconds it takes for an NPC on which the Engage
# command has been used to automatically Disengage
Engage Timeout in Seconds: 150

# Default values for triggers

Click Trigger Default Cooldown in Seconds: 2.0

Damage Trigger Default Cooldown in Seconds: 0.5

Proximity Trigger Default Cooldown in Seconds: 1.0
Proximity Trigger Default Range in Blocks: 10

Location Trigger Default Cooldown in Seconds: 5.0
Location Trigger Default Range in Blocks: 2

Chat Trigger Default Cooldown in Seconds: 2.0
Chat Trigger Default Range in Blocks: 3

# Whether the Click Trigger can be activated with a left click
# when the Damage Trigger of the NPC is disabled
Click Trigger Allows Left Click: false

# The format in which a message from a player to an NPC appears
# to the player
Chat to NPC Format: "You -> <npc.name.nickname>: <text>"

# The format in which a message from a player to an NPC appears
# to bystander players
Chat to NPC Bystanders Format: "<player.name> -> <npc.name.nickname>: <text>"
# The distance from which a message from a player to an NPC
# appears to bystander players
Chat to NPC Bystanders Range: 4

# Whether a player can chat with an NPC only when there are no
# blocks between them
Chat Only When Having Line of Sight to NPC: true
# Whether a player can chat with an NPC only when looking in
# the NPC's direction
Chat Only When Looking at NPC: true

# Whether chatting with an NPC without matching a chat trigger
# will make the text appear in the global chat
Chat Globally If Failed Chat Triggers: false
# Whether chatting with an NPC that does not have a chat trigger
# will make the text appear in the global chat
Chat Globally If No Chat Triggers: false
# Whether chatting with an NPC that isn't interactable will
# make the text appear in the global chat 
Chat Globally If Not Interactable: false

# Whether scripts should also be detected when they are placed
# inside subfolders of the scripts folder
Load Scripts in Subfolders: true